[package]
name = "pcap-sys"
version = "0.1.0"
authors = ["Danny Browning <danny.browning@protectwise.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.46"
cc = "1.0"
env_logger = "0.6"
log = "0.4"
pkg-config = "0.3"
